
GET http://127.0.0.1:3000/user-api/users
###
POST http://127.0.0.1:3000/user-api/users
Content-Type: application/json

{
  "name": "John",
  "age": 20,
  "id": 3003
}
###
PUT http://127.0.0.1:3000/user-api/users/3003
Content-Type: application/json

{
  "name": "John",
  "age": 61,
  "id": 3003
}

###Read a user by id
GET http://localhost:3000/user-api/users/2002


###
DELETE http://127.0.0.1:3000/user-api/users/2002




###
GET http://localhost:3000/product-api/products
###
GET http://localhost:3000/product-api-id/products/100
###
GET http://localhost:3000/product-api-brand/products/Apple
###
POST http://localhost:3000/product-api/products
Content-Type: application/json

{
  "productID": 100,
  "name": "Laptop",
  "price": 75000,
  "brand":"HP"
}

###
PUT http://localhost:3000/product-api/products/200
###
DELETE http://localhost:3000/product-api/products/300